name: "CodeQL"

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  # schedule:
  #   - cron: '31 5 * * 2'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ 'windows-latest' }}
    timeout-minutes: ${{ 360 }}
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: java-kotlin
          build-mode: none # This mode only analyzes Java. Set this to 'autobuild' or 'manual' to analyze Kotlin too.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install 7-Zip
      run: |
        choco install 7zip.install -y
        echo "C:\Program Files\7-Zip" >> $env:GITHUB_PATH

    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: "Liberica"
    #     java-version: 1.8
    #     java-package: jdk+fx
    #     architecture: x64

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    - name: Upload a Build Artifact
      id: upload-build-artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-queries-builtin.qls
        path: D:\a\_temp\codeql_databases\java.zip

    - name: Package CodeQL directory
      run: |
        7z a C:\CodeQL.7z C:\hostedtoolcache\windows\CodeQL

    - name: Upload a CodeQL Runtime Artifact
      id: upload-CodeQL-Runtime-artifact
      uses: actions/upload-artifact@v4
      with:
        name: CodeQL-Runtime
        path: C:\CodeQL.7z
        # path: C:\hostedtoolcache\windows\CodeQL

    # - name: Upload a Build Artifact
    #   id: upload-build-artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     # Artifact name
    #     name: # optional, default is artifact
    #       java-queries-builtin.qls
    #     # A file, directory or wildcard pattern that describes what to upload
    #     path:
    #       D:\a\_temp\codeql_databases\java.zip
    #     # The desired behavior if no files are found using the provided path.
